SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NexusLocations](
	[LocationId] [int] NOT NULL,
	[LocationName] [varchar](50) NOT NULL,
	[LocationDescription] [varchar](200) NULL,
	[Notes] [varchar](200) NULL,
	[IsActive] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NexusLocations] ADD  CONSTRAINT [PK_NexusLocations] PRIMARY KEY CLUSTERED 
(
	[LocationId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [Index_NexusLocations_LocationName_Unique] ON [dbo].[NexusLocations]
(
	[LocationName] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NexusLocations] ADD  CONSTRAINT [DEFAULT_NexusLocations_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO